In [1]:
import pandas as pd

### Removing unnecessary dates

In [2]:
# Load the merged data
merged_data = pd.read_csv('merged data.csv')  # Update with the correct file path
merged_data

,Open,High,Low,Close,Change,Per Change (%),Turnover,Date (AD),Date (BS),Date,...,Remmittance,Year,Month,Start_Date_AD,End_Date_AD,MACD,MACD_Signal,RSI,MFI,ATR
0,1806.60,1820.96,1801.41,1803.74,-16.14,-0.89,5.931860e+08,10/16/2016,6/30/2073,2073/06,...,171.80,2073,6,9/17/2016,10/16/2016,-11.195751,-5.196812,46.400901,28.590279,41.811429
1,1806.60,1822.41,1806.39,1819.88,13.28,0.74,9.916900e+08,10/6/2016,6/20/2073,2073/06,...,171.80,2073,6,9/17/2016,10/16/2016,-5.328358,-5.223121,47.506351,24.914718,40.550000
2,1798.50,1806.70,1794.58,1806.60,8.10,0.45,9.188510e+08,10/5/2016,6/19/2073,2073/06,...,171.80,2073,6,9/17/2016,10/16/2016,-1.730049,-4.524507,44.762275,26.465051,40.837143
3,1780.41,1800.50,1780.41,1798.50,18.10,1.02,1.087990e+09,10/4/2016,6/18/2073,2073/06,...,171.80,2073,6,9/17/2016,10/16/2016,0.462700,-3.527065,46.413559,27.481393,40.238571
4,1763.90,1784.05,1763.67,1780.40,16.62,0.94,7.618340e+08,10/3/2016,6/17/2073,2073/06,...,171.80,2073,6,9/17/2016,10/16/2016,0.731519,-2.675348,45.881258,28.592510,41.130714
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1606,2045.85,2052.02,2009.10,2013.93,-31.52,-1.54,1.550583e+09,8/24/2023,5/7/2080,2080/05,...,228.37,2080,5,8/18/2023,9/17/2023,-25.418704,-25.932105,35.222295,66.891689,47.171429
1607,2016.79,2047.87,2016.06,2045.45,29.47,1.46,1.510489e+09,8/23/2023,5/6/2080,2080/05,...,228.37,2080,5,8/18/2023,9/17/2023,-20.009297,-24.747543,63.748720,78.016531,36.560714
1608,1998.14,2015.98,1990.34,2015.98,17.69,0.88,1.332565e+09,8/22/2023,5/5/2080,2080/05,...,228.37,2080,5,8/18/2023,9/17/2023,-17.894015,-23.376838,51.591607,69.701917,37.486429
1609,2012.45,2019.41,1991.94,1998.28,-12.93,-0.64,1.408982e+09,8/21/2023,5/4/2080,2080/05,...,228.37,2080,5,8/18/2023,9/17/2023,-17.444788,-22.190428,55.941648,68.498765,36.299286
1610,2033.20,2034.49,2008.13,2011.22,-21.91,-1.07,1.447409e+09,8/20/2023,5/3/2080,2080/05,...,228.37,2080,5,8/18/2023,9/17/2023,-15.861778,-20.924698,54.808494,77.370612,35.690000

In [4]:
min_val = merged_data['Close'].min()
max_val = merged_data['Close'].max()
print(min_val)
print(max_val)

1100.58
3198.6

In [4]:
# Remove the specified columns
columns_to_remove = ['Date (AD)', 'Date (BS)', 'Date', 'Year', 'Start_Date_AD', 'End_Date_AD']
merged_data_cleaned = merged_data.drop(columns=columns_to_remove, errors='ignore')

In [7]:
merged_data_cleaned.columns

Index(['Open', 'High', 'Low', 'Close', 'Change', 'Per Change (%)', 'Turnover',
       'Total deposit/GDP', 'Total credit/GDP', 'Total credit/Total deposit',
       'Total liquid asset/total deposit', 'Interest on Savings',
       'Interest on fixed deposit', 'Interest on credit', 'Remmittance',
       'Month', 'MACD', 'MACD_Signal', 'RSI', 'MFI', 'ATR'],
      dtype='object')

In [8]:
# Load the merged data
merged_data = pd.read_csv('merged data.csv')  

min_val = merged_data['Close'].min()
max_val = merged_data['Close'].max()

# Normalizing the numeric columns using Min-Max Scaling
for column in merged_data_cleaned.select_dtypes(include=['float64', 'int64']).columns:
    if column != 'Month':
        min_val = merged_data_cleaned[column].min()
        max_val = merged_data_cleaned[column].max()
        merged_data_cleaned[column] = (merged_data_cleaned[column] - min_val) / 
        (max_val - min_val) if max_val != min_val else merged_data_cleaned[column]
        
# Create 12 new columns for each month (1 for Baisakh, 2 for Jestha, etc.)
month_names = ['Baisakh', 'Jestha', 'Ashar', 'Shrawan', 'Bhadra', 'Asoj', 'Kartik', 
               'Mangsir', 'Poush', 'Magh', 'Falgun', 'Chaitra']
for month in month_names:
    merged_data_cleaned[month] = (merged_data_cleaned['Month'] == (month_names.index(month) + 1)).astype(int)
merged_data_cleaned

In [9]:
merged_data_cleaned.head(380)

,Open,High,Low,Close,Change,Per Change (%),Turnover,Total deposit/GDP,Total credit/GDP,Total credit/Total deposit,...,Interest on Savings,Interest on fixed deposit,Interest on credit,Remmittance,Month,MACD,MACD_Signal,RSI,MFI,ATR
0,0.334815,0.337538,0.337781,0.335154,0.375771,0.425620,0.027240,0.374339,0.107658,0.000000,...,0.003690,0.000000,0.041304,0.099785,6,0.406131,0.438929,0.449366,0.291895,0.251635
1,0.334815,0.338221,0.340176,0.342847,0.478898,0.560331,0.045651,0.374339,0.107658,0.000000,...,0.003690,0.000000,0.041304,0.099785,6,0.429882,0.438803,0.461423,0.251860,0.242033
2,0.330972,0.330819,0.334497,0.336517,0.460740,0.536364,0.042286,0.374339,0.107658,0.000000,...,0.003690,0.000000,0.041304,0.099785,6,0.444447,0.442135,0.431495,0.268747,0.244219
3,0.322389,0.327897,0.327683,0.332657,0.495794,0.583471,0.050101,0.374339,0.107658,0.000000,...,0.003690,0.000000,0.041304,0.099785,6,0.453323,0.446891,0.449505,0.279817,0.239663
4,0.314555,0.320146,0.319634,0.324029,0.490606,0.576860,0.035031,0.374339,0.107658,0.000000,...,0.003690,0.000000,0.041304,0.099785,6,0.454412,0.450953,0.443699,0.291919,0.246454
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,0.083793,0.083066,0.077062,0.085590,0.441461,0.515702,0.013364,0.028199,0.065555,0.498326,...,0.420664,0.834879,0.778261,0.473069,1,0.484501,0.555357,0.364153,0.452353,0.275427
376,0.065625,0.069859,0.068714,0.069933,0.450680,0.533884,0.012283,0.093409,0.098615,0.462157,...,0.439114,0.860853,0.858696,0.535772,2,0.450725,0.536857,0.301753,0.419630,0.284670
377,0.065625,0.065255,0.065425,0.067440,0.442197,0.518182,0.008609,0.093409,0.098615,0.462157,...,0.439114,0.860853,0.858696,0.535772,2,0.422582,0.515426,0.265342,0.362919,0.278826
378,0.066541,0.066080,0.063218,0.066100,0.425582,0.485950,0.012358,0.093409,0.098615,0.462157,...,0.439114,0.860853,0.858696,0.535772,2,0.399954,0.492950,0.268518,0.367532,0.269947
379,0.062010,0.069779,0.060025,0.067020,0.465823,0.563636,0.016977,0.093409,0.098615,0.462157,...,0.439114,0.860853,0.858696,0.535772,2,0.383435,0.471077,0.286323,0.408312,0.272225

### One Hot Encoding for month

In [10]:
# Create 12 new columns for each month (1 for Baisakh, 2 for Jestha, etc.)
month_names = ['Baisakh', 'Jestha', 'Ashar', 'Shrawan', 'Bhadra', 'Asoj', 'Kartik', 'Mangsir', 'Poush', 'Magh', 'Falgun', 'Chaitra']
for month in month_names:
    merged_data_cleaned[month] = (merged_data_cleaned['Month'] == (month_names.index(month) + 1)).astype(int)
merged_data_cleaned

,Open,High,Low,Close,Change,Per Change (%),Turnover,Total deposit/GDP,Total credit/GDP,Total credit/Total deposit,...,Ashar,Shrawan,Bhadra,Asoj,Kartik,Mangsir,Poush,Magh,Falgun,Chaitra
0,0.334815,0.337538,0.337781,0.335154,0.375771,0.425620,0.027240,0.374339,0.107658,0.000000,...,0,0,0,1,0,0,0,0,0,0
1,0.334815,0.338221,0.340176,0.342847,0.478898,0.560331,0.045651,0.374339,0.107658,0.000000,...,0,0,0,1,0,0,0,0,0,0
2,0.330972,0.330819,0.334497,0.336517,0.460740,0.536364,0.042286,0.374339,0.107658,0.000000,...,0,0,0,1,0,0,0,0,0,0
3,0.322389,0.327897,0.327683,0.332657,0.495794,0.583471,0.050101,0.374339,0.107658,0.000000,...,0,0,0,1,0,0,0,0,0,0
4,0.314555,0.320146,0.319634,0.324029,0.490606,0.576860,0.035031,0.374339,0.107658,0.000000,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1606,0.448334,0.446411,0.437650,0.435339,0.321859,0.371901,0.071473,0.709905,0.452105,0.278634,...,0,0,1,0,0,0,0,0,0,0
1607,0.434546,0.444456,0.440997,0.450363,0.535649,0.619835,0.069621,0.709905,0.452105,0.278634,...,0,0,1,0,0,0,0,0,0,0
1608,0.425697,0.429430,0.428629,0.436316,0.494356,0.571901,0.061400,0.709905,0.452105,0.278634,...,0,0,1,0,0,0,0,0,0,0
1609,0.432487,0.431046,0.429398,0.427880,0.387023,0.446281,0.064931,0.709905,0.452105,0.278634,...,0,0,1,0,0,0,0,0,0,0
1610,0.442332,0.438151,0.437184,0.434047,0.355545,0.410744,0.066707,0.709905,0.452105,0.278634,...,0,0,1,0,0,0,0,0,0,0

In [23]:
merged_data_cleaned.to_csv('final_data.csv', index=False)